# Configuration for welcome - https://github.com/behaviorbot/welcome

# Configuration for new-issue-welcome - https://github.com/behaviorbot/new-issue-welcome
# Comment to be posted to on first time issues

newIssueWelcomeComment: >
  Hello there!👋 Welcome to the project!🚀⚡
  
  
  Thank you and congrats🎉 for opening your very first issue in this project.
  Please adhere to our [Code of Conduct](https://github.com/rexdivakar/Notifly/blob/main/CODE_OF_CONDUCT.md).
  Please make sure not to start working on the issue, unless you get assigned to it.😄
  Feel free to join us on [OpenSource-Dev-Community](https://discord.gg/tTJQxvSaDP)✨ Hope you have a great time there!😄
  
  
# Configuration for new-pr-welcome - https://github.com/behaviorbot/new-pr-welcome
# Comment to be posted to on PRs from first time contributors in your repository

newPRWelcomeComment: >
  Hello there!👋 Welcome to the project!💖
  
  
  Thank you and congrats🎉 for opening your first pull request in this project.
  Please make sure you have followed our [Contributing Guidelines](https://github.com/rexdivakar/Notifly/blob/main/CONTRIBUTING.md).🙌🙌 We will get back to you as soon as we can 😄.
  Feel free to join us on [OpenSource-Dev-Community](https://discord.gg/tTJQxvSaDP)✨ Hope you have a great time there!😄
  
# Configuration for first-pr-merge - https://github.com/behaviorbot/first-pr-merge
# Comment to be posted to on pull requests merged by a first time user

firstPRMergeComment: >
  Congrats on merging your first pull request! 🎉 All the best for your amazing open source journey ahead 🚀.
